/**
 * The 74-series library.
 *
 * Pin tables are transcribed from the standard 74LS datasheet pinouts. Where a part
 * has an unusual arrangement - the 7483 puts VCC on pin 5 and GND on pin 12, the 7476
 * puts VCC on pin 5 and GND on pin 13 - the table says so and the `notes` field tells
 * the student, because that is exactly the mistake a lab bench punishes.
 */

import type { ComponentDefinition } from '../ComponentDefinition';
import { gate, ttl } from './builder';

const IC_7400 = ttl({
  partNumber: '7400',
  name: 'Quad 2-Input NAND',
  description: 'Four independent 2-input NAND gates in one 14-pin package.',
  keywords: ['nand', 'gate', 'quad', 'logic'],
  pinCount: 14,
  pins: [
    ['1A', 'INPUT', 'in'],
    ['1B', 'INPUT', 'in'],
    ['1Y', 'OUTPUT', 'out'],
    ['2A', 'INPUT', 'in'],
    ['2B', 'INPUT', 'in'],
    ['2Y', 'OUTPUT', 'out'],
    ['GND', 'GROUND', 'power'],
    ['3Y', 'OUTPUT', 'out'],
    ['3A', 'INPUT', 'in'],
    ['3B', 'INPUT', 'in'],
    ['4Y', 'OUTPUT', 'out'],
    ['4A', 'INPUT', 'in'],
    ['4B', 'INPUT', 'in'],
    ['VCC', 'POWER', 'power'],
  ],
  gates: [
    gate('Gate 1', 'nand', [1, 2], 3),
    gate('Gate 2', 'nand', [4, 5], 6),
    gate('Gate 3', 'nand', [9, 10], 8),
    gate('Gate 4', 'nand', [12, 13], 11),
  ],
  propagationDelayNs: 9,
  datasheet: {
    functionSummary: 'Y = NOT (A AND B) for each of the four gates.',
    notes: ['VCC is pin 14, GND is pin 7.', 'An unconnected TTL input floats high but is unreliable; tie unused inputs to a known level.'],
  },
});

const IC_7402 = ttl({
  partNumber: '7402',
  name: 'Quad 2-Input NOR',
  description: 'Four independent 2-input NOR gates. Outputs come first in each group.',
  keywords: ['nor', 'gate', 'quad', 'logic'],
  pinCount: 14,
  pins: [
    ['1Y', 'OUTPUT', 'out'],
    ['1A', 'INPUT', 'in'],
    ['1B', 'INPUT', 'in'],
    ['2Y', 'OUTPUT', 'out'],
    ['2A', 'INPUT', 'in'],
    ['2B', 'INPUT', 'in'],
    ['GND', 'GROUND', 'power'],
    ['3Y', 'OUTPUT', 'out'],
    ['3A', 'INPUT', 'in'],
    ['3B', 'INPUT', 'in'],
    ['4Y', 'OUTPUT', 'out'],
    ['4A', 'INPUT', 'in'],
    ['4B', 'INPUT', 'in'],
    ['VCC', 'POWER', 'power'],
  ],
  gates: [
    gate('Gate 1', 'nor', [2, 3], 1),
    gate('Gate 2', 'nor', [5, 6], 4),
    gate('Gate 3', 'nor', [9, 10], 8),
    gate('Gate 4', 'nor', [12, 13], 11),
  ],
  propagationDelayNs: 10,
  datasheet: {
    functionSummary: 'Y = NOT (A OR B) for each of the four gates.',
    notes: ['Unlike the 7400 the output is the first pin of each gate group.'],
  },
});

const IC_7404 = ttl({
  partNumber: '7404',
  name: 'Hex Inverter',
  description: 'Six independent NOT gates.',
  keywords: ['not', 'inverter', 'hex', 'logic'],
  pinCount: 14,
  pins: [
    ['1A', 'INPUT', 'in'],
    ['1Y', 'OUTPUT', 'out'],
    ['2A', 'INPUT', 'in'],
    ['2Y', 'OUTPUT', 'out'],
    ['3A', 'INPUT', 'in'],
    ['3Y', 'OUTPUT', 'out'],
    ['GND', 'GROUND', 'power'],
    ['4Y', 'OUTPUT', 'out'],
    ['4A', 'INPUT', 'in'],
    ['5Y', 'OUTPUT', 'out'],
    ['5A', 'INPUT', 'in'],
    ['6Y', 'OUTPUT', 'out'],
    ['6A', 'INPUT', 'in'],
    ['VCC', 'POWER', 'power'],
  ],
  gates: [
    gate('Gate 1', 'not', [1], 2),
    gate('Gate 2', 'not', [3], 4),
    gate('Gate 3', 'not', [5], 6),
    gate('Gate 4', 'not', [9], 8),
    gate('Gate 5', 'not', [11], 10),
    gate('Gate 6', 'not', [13], 12),
  ],
  propagationDelayNs: 9,
  datasheet: { functionSummary: 'Y = NOT A for each of the six inverters.' },
});

const IC_7408 = ttl({
  partNumber: '7408',
  name: 'Quad 2-Input AND',
  description: 'Four independent 2-input AND gates.',
  keywords: ['and', 'gate', 'quad', 'logic'],
  pinCount: 14,
  pins: [
    ['1A', 'INPUT', 'in'],
    ['1B', 'INPUT', 'in'],
    ['1Y', 'OUTPUT', 'out'],
    ['2A', 'INPUT', 'in'],
    ['2B', 'INPUT', 'in'],
    ['2Y', 'OUTPUT', 'out'],
    ['GND', 'GROUND', 'power'],
    ['3Y', 'OUTPUT', 'out'],
    ['3A', 'INPUT', 'in'],
    ['3B', 'INPUT', 'in'],
    ['4Y', 'OUTPUT', 'out'],
    ['4A', 'INPUT', 'in'],
    ['4B', 'INPUT', 'in'],
    ['VCC', 'POWER', 'power'],
  ],
  gates: [
    gate('Gate 1', 'and', [1, 2], 3),
    gate('Gate 2', 'and', [4, 5], 6),
    gate('Gate 3', 'and', [9, 10], 8),
    gate('Gate 4', 'and', [12, 13], 11),
  ],
  propagationDelayNs: 12,
  datasheet: { functionSummary: 'Y = A AND B for each of the four gates.' },
});

const IC_7410 = ttl({
  partNumber: '7410',
  name: 'Triple 3-Input NAND',
  description: 'Three independent 3-input NAND gates.',
  keywords: ['nand', 'gate', 'triple', '3-input', 'logic'],
  pinCount: 14,
  pins: [
    ['1A', 'INPUT', 'in'],
    ['1B', 'INPUT', 'in'],
    ['2A', 'INPUT', 'in'],
    ['2B', 'INPUT', 'in'],
    ['2C', 'INPUT', 'in'],
    ['2Y', 'OUTPUT', 'out'],
    ['GND', 'GROUND', 'power'],
    ['3Y', 'OUTPUT', 'out'],
    ['3A', 'INPUT', 'in'],
    ['3B', 'INPUT', 'in'],
    ['3C', 'INPUT', 'in'],
    ['1Y', 'OUTPUT', 'out'],
    ['1C', 'INPUT', 'in'],
    ['VCC', 'POWER', 'power'],
  ],
  gates: [
    gate('Gate 1', 'nand', [1, 2, 13], 12),
    gate('Gate 2', 'nand', [3, 4, 5], 6),
    gate('Gate 3', 'nand', [9, 10, 11], 8),
  ],
  propagationDelayNs: 10,
  datasheet: {
    functionSummary: 'Y = NOT (A AND B AND C) for each of the three gates.',
    notes: ['Gate 1 is split across the package: inputs on pins 1, 2 and 13, output on pin 12.'],
  },
});

const IC_7420 = ttl({
  partNumber: '7420',
  name: 'Dual 4-Input NAND',
  description: 'Two independent 4-input NAND gates. Pins 3 and 11 are not connected.',
  keywords: ['nand', 'gate', 'dual', '4-input', 'logic'],
  pinCount: 14,
  pins: [
    ['1A', 'INPUT', 'in'],
    ['1B', 'INPUT', 'in'],
    ['NC', 'PASSIVE', 'passive', { note: 'Not connected internally.' }],
    ['1C', 'INPUT', 'in'],
    ['1D', 'INPUT', 'in'],
    ['1Y', 'OUTPUT', 'out'],
    ['GND', 'GROUND', 'power'],
    ['2Y', 'OUTPUT', 'out'],
    ['2A', 'INPUT', 'in'],
    ['2B', 'INPUT', 'in'],
    ['NC', 'PASSIVE', 'passive', { note: 'Not connected internally.' }],
    ['2C', 'INPUT', 'in'],
    ['2D', 'INPUT', 'in'],
    ['VCC', 'POWER', 'power'],
  ],
  gates: [
    gate('Gate 1', 'nand', [1, 2, 4, 5], 6),
    gate('Gate 2', 'nand', [9, 10, 12, 13], 8),
  ],
  propagationDelayNs: 10,
  datasheet: { functionSummary: 'Y = NOT (A AND B AND C AND D) for each of the two gates.' },
});

const IC_7427 = ttl({
  partNumber: '7427',
  name: 'Triple 3-Input NOR',
  description: 'Three independent 3-input NOR gates.',
  keywords: ['nor', 'gate', 'triple', '3-input', 'logic'],
  pinCount: 14,
  pins: [
    ['1A', 'INPUT', 'in'],
    ['1B', 'INPUT', 'in'],
    ['2A', 'INPUT', 'in'],
    ['2B', 'INPUT', 'in'],
    ['2C', 'INPUT', 'in'],
    ['2Y', 'OUTPUT', 'out'],
    ['GND', 'GROUND', 'power'],
    ['3Y', 'OUTPUT', 'out'],
    ['3A', 'INPUT', 'in'],
    ['3B', 'INPUT', 'in'],
    ['3C', 'INPUT', 'in'],
    ['1Y', 'OUTPUT', 'out'],
    ['1C', 'INPUT', 'in'],
    ['VCC', 'POWER', 'power'],
  ],
  gates: [
    gate('Gate 1', 'nor', [1, 2, 13], 12),
    gate('Gate 2', 'nor', [3, 4, 5], 6),
    gate('Gate 3', 'nor', [9, 10, 11], 8),
  ],
  propagationDelayNs: 10,
  datasheet: { functionSummary: 'Y = NOT (A OR B OR C) for each of the three gates.' },
});

const IC_7430 = ttl({
  partNumber: '7430',
  name: '8-Input NAND',
  description: 'A single 8-input NAND gate.',
  keywords: ['nand', 'gate', '8-input', 'logic'],
  pinCount: 14,
  pins: [
    ['A', 'INPUT', 'in'],
    ['B', 'INPUT', 'in'],
    ['C', 'INPUT', 'in'],
    ['D', 'INPUT', 'in'],
    ['E', 'INPUT', 'in'],
    ['F', 'INPUT', 'in'],
    ['GND', 'GROUND', 'power'],
    ['Y', 'OUTPUT', 'out'],
    ['NC', 'PASSIVE', 'passive', { note: 'Not connected internally.' }],
    ['NC', 'PASSIVE', 'passive', { note: 'Not connected internally.' }],
    ['G', 'INPUT', 'in'],
    ['H', 'INPUT', 'in'],
    ['NC', 'PASSIVE', 'passive', { note: 'Not connected internally.' }],
    ['VCC', 'POWER', 'power'],
  ],
  gates: [gate('Gate 1', 'nand', [1, 2, 3, 4, 5, 6, 11, 12], 8)],
  propagationDelayNs: 12,
  datasheet: { functionSummary: 'Y = NOT (A AND B AND C AND D AND E AND F AND G AND H).' },
});

const IC_7432 = ttl({
  partNumber: '7432',
  name: 'Quad 2-Input OR',
  description: 'Four independent 2-input OR gates.',
  keywords: ['or', 'gate', 'quad', 'logic'],
  pinCount: 14,
  pins: [
    ['1A', 'INPUT', 'in'],
    ['1B', 'INPUT', 'in'],
    ['1Y', 'OUTPUT', 'out'],
    ['2A', 'INPUT', 'in'],
    ['2B', 'INPUT', 'in'],
    ['2Y', 'OUTPUT', 'out'],
    ['GND', 'GROUND', 'power'],
    ['3Y', 'OUTPUT', 'out'],
    ['3A', 'INPUT', 'in'],
    ['3B', 'INPUT', 'in'],
    ['4Y', 'OUTPUT', 'out'],
    ['4A', 'INPUT', 'in'],
    ['4B', 'INPUT', 'in'],
    ['VCC', 'POWER', 'power'],
  ],
  gates: [
    gate('Gate 1', 'or', [1, 2], 3),
    gate('Gate 2', 'or', [4, 5], 6),
    gate('Gate 3', 'or', [9, 10], 8),
    gate('Gate 4', 'or', [12, 13], 11),
  ],
  propagationDelayNs: 12,
  datasheet: { functionSummary: 'Y = A OR B for each of the four gates.' },
});

const IC_7486 = ttl({
  partNumber: '7486',
  name: 'Quad 2-Input XOR',
  description: 'Four independent 2-input exclusive-OR gates.',
  keywords: ['xor', 'exclusive', 'gate', 'quad', 'logic', 'parity'],
  pinCount: 14,
  pins: [
    ['1A', 'INPUT', 'in'],
    ['1B', 'INPUT', 'in'],
    ['1Y', 'OUTPUT', 'out'],
    ['2A', 'INPUT', 'in'],
    ['2B', 'INPUT', 'in'],
    ['2Y', 'OUTPUT', 'out'],
    ['GND', 'GROUND', 'power'],
    ['3Y', 'OUTPUT', 'out'],
    ['3A', 'INPUT', 'in'],
    ['3B', 'INPUT', 'in'],
    ['4Y', 'OUTPUT', 'out'],
    ['4A', 'INPUT', 'in'],
    ['4B', 'INPUT', 'in'],
    ['VCC', 'POWER', 'power'],
  ],
  gates: [
    gate('Gate 1', 'xor', [1, 2], 3),
    gate('Gate 2', 'xor', [4, 5], 6),
    gate('Gate 3', 'xor', [9, 10], 8),
    gate('Gate 4', 'xor', [12, 13], 11),
  ],
  propagationDelayNs: 12,
  datasheet: {
    functionSummary: 'Y = A XOR B for each of the four gates.',
    notes: ['Two XOR gates and two AND gates make a half adder; this part plus a 7408 builds one.'],
  },
});

const IC_7447 = ttl({
  partNumber: '7447',
  name: 'BCD to 7-Segment Decoder',
  description:
    'Decodes a 4-bit BCD input to active-low seven-segment drive lines for a common-anode display.',
  keywords: ['bcd', 'decoder', 'seven segment', '7segment', 'display', 'driver'],
  pinCount: 16,
  pins: [
    ['B', 'INPUT', 'in'],
    ['C', 'INPUT', 'in'],
    ['LT', 'INPUT', 'in', { activeLow: true, note: 'Lamp test: pull low to light every segment.' }],
    ['BI/RBO', 'BIDIRECTIONAL', 'inout', { activeLow: true, note: 'Blanking input / ripple blanking output.' }],
    ['RBI', 'INPUT', 'in', { activeLow: true, note: 'Ripple blanking input: blanks a leading zero.' }],
    ['D', 'INPUT', 'in'],
    ['A', 'INPUT', 'in'],
    ['GND', 'GROUND', 'power'],
    ['e', 'OUTPUT', 'out', { activeLow: true }],
    ['d', 'OUTPUT', 'out', { activeLow: true }],
    ['c', 'OUTPUT', 'out', { activeLow: true }],
    ['b', 'OUTPUT', 'out', { activeLow: true }],
    ['a', 'OUTPUT', 'out', { activeLow: true }],
    ['g', 'OUTPUT', 'out', { activeLow: true }],
    ['f', 'OUTPUT', 'out', { activeLow: true }],
    ['VCC', 'POWER', 'power'],
  ],
  model: 'ic7447',
  propagationDelayNs: 25,
  datasheet: {
    functionSummary: 'BCD in on A-D, seven active-low open-collector segment outputs a-g.',
    notes: [
      'Segment outputs are active LOW and open collector: they sink current from a common-anode display.',
      'A is the least significant bit and sits on pin 7, D the most significant on pin 6.',
    ],
  },
});

const IC_7474 = ttl({
  partNumber: '7474',
  name: 'Dual D Flip-Flop',
  description:
    'Two positive-edge-triggered D flip-flops, each with an asynchronous active-low preset and clear.',
  keywords: ['flip flop', 'flipflop', 'd flip-flop', 'dff', 'sequential', 'register', 'latch'],
  pinCount: 14,
  pins: [
    ['1CLR', 'RESET', 'in', { activeLow: true, note: 'Asynchronous clear, active low.' }],
    ['1D', 'INPUT', 'in'],
    ['1CLK', 'CLOCK', 'in', { note: 'Rising edge triggered.' }],
    ['1PRE', 'SET', 'in', { activeLow: true, note: 'Asynchronous preset, active low.' }],
    ['1Q', 'OUTPUT', 'out'],
    ['1Q̅', 'OUTPUT', 'out', { note: 'Complement of 1Q.' }],
    ['GND', 'GROUND', 'power'],
    ['2Q̅', 'OUTPUT', 'out', { note: 'Complement of 2Q.' }],
    ['2Q', 'OUTPUT', 'out'],
    ['2PRE', 'SET', 'in', { activeLow: true }],
    ['2CLK', 'CLOCK', 'in', { note: 'Rising edge triggered.' }],
    ['2D', 'INPUT', 'in'],
    ['2CLR', 'RESET', 'in', { activeLow: true }],
    ['VCC', 'POWER', 'power'],
  ],
  model: 'ic7474',
  propagationDelayNs: 20,
  maxClockMHz: 25,
  datasheet: {
    functionSummary: 'Q takes the value of D on each rising clock edge.',
    notes: [
      'PRE and CLR are asynchronous and active LOW: tie them HIGH for normal clocked operation.',
      'Holding PRE and CLR low together forces both Q and Q-bar high, which is why the datasheet calls it a forbidden state.',
    ],
  },
});

const IC_7476 = ttl({
  partNumber: '7476',
  name: 'Dual JK Flip-Flop',
  description:
    'Two JK flip-flops with asynchronous active-low preset and clear. Note the unusual power pins.',
  keywords: ['jk', 'flip flop', 'flipflop', 'sequential', 'toggle'],
  pinCount: 16,
  pins: [
    ['1CLK', 'CLOCK', 'in', { note: 'Data is accepted while clock is high and transferred on the falling edge.' }],
    ['1PRE', 'SET', 'in', { activeLow: true }],
    ['1CLR', 'RESET', 'in', { activeLow: true }],
    ['1J', 'INPUT', 'in'],
    ['VCC', 'POWER', 'power'],
    ['2CLK', 'CLOCK', 'in'],
    ['2PRE', 'SET', 'in', { activeLow: true }],
    ['2CLR', 'RESET', 'in', { activeLow: true }],
    ['2J', 'INPUT', 'in'],
    ['2K', 'INPUT', 'in'],
    ['2Q', 'OUTPUT', 'out'],
    ['2Q̅', 'OUTPUT', 'out'],
    ['GND', 'GROUND', 'power'],
    ['1K', 'INPUT', 'in'],
    ['1Q̅', 'OUTPUT', 'out'],
    ['1Q', 'OUTPUT', 'out'],
  ],
  model: 'ic7476',
  propagationDelayNs: 20,
  maxClockMHz: 20,
  datasheet: {
    functionSummary: 'J=K=1 toggles, J=1/K=0 sets, J=0/K=1 clears, J=K=0 holds.',
    notes: [
      'VCC is pin 5 and GND is pin 13 on this part, not the usual corner pins. Wiring it like a 7474 destroys it.',
      'ProtoLab models the master-slave transfer on the falling clock edge.',
    ],
  },
});

const IC_7483 = ttl({
  partNumber: '7483',
  name: '4-Bit Binary Full Adder',
  description:
    'Adds two 4-bit words with carry in and carry out, using fast internal carry lookahead.',
  keywords: ['adder', 'full adder', 'arithmetic', 'carry', '4-bit', 'sum'],
  pinCount: 16,
  pins: [
    ['A4', 'INPUT', 'in'],
    ['S3', 'OUTPUT', 'out'],
    ['A3', 'INPUT', 'in'],
    ['B3', 'INPUT', 'in'],
    ['VCC', 'POWER', 'power'],
    ['S2', 'OUTPUT', 'out'],
    ['B2', 'INPUT', 'in'],
    ['A2', 'INPUT', 'in'],
    ['S1', 'OUTPUT', 'out'],
    ['A1', 'INPUT', 'in'],
    ['B1', 'INPUT', 'in'],
    ['GND', 'GROUND', 'power'],
    ['C0', 'INPUT', 'in', { note: 'Carry in.' }],
    ['C4', 'OUTPUT', 'out', { note: 'Carry out.' }],
    ['S4', 'OUTPUT', 'out'],
    ['B4', 'INPUT', 'in'],
  ],
  model: 'ic7483',
  propagationDelayNs: 16,
  datasheet: {
    functionSummary: 'S = A + B + C0, with the fifth bit appearing on C4.',
    notes: [
      'VCC is pin 5 and GND is pin 12. This part does not use the corner pins for power.',
      'A1/B1/S1 are the least significant bit.',
    ],
  },
});

const IC_7490 = ttl({
  partNumber: '7490',
  name: 'Decade Counter',
  description:
    'A divide-by-two and a divide-by-five counter in one package; cascade them for a decade counter.',
  keywords: ['counter', 'decade', 'bcd', 'divide', 'ripple', 'sequential'],
  pinCount: 14,
  pins: [
    ['CKB', 'CLOCK', 'in', { note: 'Clock for the divide-by-five section. Falling edge.' }],
    ['R0(1)', 'RESET', 'in', { note: 'Both R0 inputs high clears the counter to 0.' }],
    ['R0(2)', 'RESET', 'in'],
    ['NC', 'PASSIVE', 'passive'],
    ['VCC', 'POWER', 'power'],
    ['R9(1)', 'SET', 'in', { note: 'Both R9 inputs high presets the counter to 9.' }],
    ['R9(2)', 'SET', 'in'],
    ['QC', 'OUTPUT', 'out'],
    ['QB', 'OUTPUT', 'out'],
    ['GND', 'GROUND', 'power'],
    ['QD', 'OUTPUT', 'out'],
    ['QA', 'OUTPUT', 'out'],
    ['NC', 'PASSIVE', 'passive'],
    ['CKA', 'CLOCK', 'in', { note: 'Clock for the divide-by-two section. Falling edge.' }],
  ],
  model: 'ic7490',
  propagationDelayNs: 20,
  maxClockMHz: 32,
  datasheet: {
    functionSummary: 'Divide-by-2 (QA) and divide-by-5 (QB QC QD) counters that cascade to BCD.',
    notes: [
      'VCC is pin 5 and GND is pin 10 on this part.',
      'For a 0-9 BCD count, drive CKA and wire QA (pin 12) to CKB (pin 1).',
    ],
  },
});

const IC_74138 = ttl({
  partNumber: '74138',
  name: '3-to-8 Line Decoder',
  description: 'Decodes three address lines to eight mutually exclusive active-low outputs.',
  keywords: ['decoder', 'demultiplexer', 'demux', '3to8', 'address', 'select'],
  pinCount: 16,
  pins: [
    ['A0', 'INPUT', 'in', { note: 'Least significant select bit.' }],
    ['A1', 'INPUT', 'in'],
    ['A2', 'INPUT', 'in', { note: 'Most significant select bit.' }],
    ['E1', 'ENABLE', 'in', { activeLow: true }],
    ['E2', 'ENABLE', 'in', { activeLow: true }],
    ['E3', 'ENABLE', 'in', { note: 'Active high enable.' }],
    ['Y7', 'OUTPUT', 'out', { activeLow: true }],
    ['GND', 'GROUND', 'power'],
    ['Y6', 'OUTPUT', 'out', { activeLow: true }],
    ['Y5', 'OUTPUT', 'out', { activeLow: true }],
    ['Y4', 'OUTPUT', 'out', { activeLow: true }],
    ['Y3', 'OUTPUT', 'out', { activeLow: true }],
    ['Y2', 'OUTPUT', 'out', { activeLow: true }],
    ['Y1', 'OUTPUT', 'out', { activeLow: true }],
    ['Y0', 'OUTPUT', 'out', { activeLow: true }],
    ['VCC', 'POWER', 'power'],
  ],
  model: 'ic74138',
  propagationDelayNs: 21,
  datasheet: {
    functionSummary:
      'The addressed output goes LOW when E1 and E2 are low and E3 is high; all others stay HIGH.',
    notes: ['Outputs are active LOW. All eight sit high when the part is disabled.'],
  },
});

const IC_74151 = ttl({
  partNumber: '74151',
  name: '8-to-1 Multiplexer',
  description: 'Selects one of eight data inputs onto a true output and its complement.',
  keywords: ['multiplexer', 'mux', '8to1', 'selector', 'data select'],
  pinCount: 16,
  pins: [
    ['D3', 'INPUT', 'in'],
    ['D2', 'INPUT', 'in'],
    ['D1', 'INPUT', 'in'],
    ['D0', 'INPUT', 'in'],
    ['Y', 'OUTPUT', 'out', { note: 'Selected data.' }],
    ['W', 'OUTPUT', 'out', { note: 'Complement of Y.' }],
    ['E', 'ENABLE', 'in', { activeLow: true, note: 'Strobe: output is forced inactive when high.' }],
    ['GND', 'GROUND', 'power'],
    ['S2', 'INPUT', 'in', { note: 'Most significant select bit (C).' }],
    ['S1', 'INPUT', 'in', { note: 'Select bit B.' }],
    ['S0', 'INPUT', 'in', { note: 'Least significant select bit (A).' }],
    ['D7', 'INPUT', 'in'],
    ['D6', 'INPUT', 'in'],
    ['D5', 'INPUT', 'in'],
    ['D4', 'INPUT', 'in'],
    ['VCC', 'POWER', 'power'],
  ],
  model: 'ic74151',
  propagationDelayNs: 22,
  datasheet: {
    functionSummary: 'Y = D[S2 S1 S0] while the strobe is low; W is the complement of Y.',
    notes: ['With the strobe high, Y is forced low and W high.'],
  },
});

const IC_74163 = ttl({
  partNumber: '74163',
  name: 'Synchronous 4-Bit Binary Counter',
  description:
    'A presettable synchronous binary counter with synchronous clear and a ripple carry output.',
  keywords: ['counter', 'binary', 'synchronous', '4-bit', 'sequential', 'load'],
  pinCount: 16,
  pins: [
    ['CLR', 'RESET', 'in', { activeLow: true, note: 'Synchronous clear: takes effect on the next rising edge.' }],
    ['CLK', 'CLOCK', 'in', { note: 'Rising edge triggered.' }],
    ['A', 'INPUT', 'in', { note: 'Parallel data, least significant bit.' }],
    ['B', 'INPUT', 'in'],
    ['C', 'INPUT', 'in'],
    ['D', 'INPUT', 'in', { note: 'Parallel data, most significant bit.' }],
    ['ENP', 'ENABLE', 'in'],
    ['GND', 'GROUND', 'power'],
    ['LOAD', 'ENABLE', 'in', { activeLow: true, note: 'Synchronous parallel load.' }],
    ['ENT', 'ENABLE', 'in', { note: 'Also gates the ripple carry output.' }],
    ['QD', 'OUTPUT', 'out'],
    ['QC', 'OUTPUT', 'out'],
    ['QB', 'OUTPUT', 'out'],
    ['QA', 'OUTPUT', 'out'],
    ['RCO', 'OUTPUT', 'out', { note: 'High when the count is 15 and ENT is high.' }],
    ['VCC', 'POWER', 'power'],
  ],
  model: 'ic74163',
  propagationDelayNs: 18,
  maxClockMHz: 25,
  datasheet: {
    functionSummary: 'Counts 0-15 on rising clock edges when ENP and ENT are both high.',
    notes: [
      'Everything about this part is synchronous: CLR and LOAD only act on a clock edge.',
      'The 74161 is the same part with an asynchronous clear.',
    ],
  },
});

const IC_74195 = ttl({
  partNumber: '74195',
  name: '4-Bit Parallel-Access Shift Register',
  description: 'Shifts right on a rising clock edge, or loads all four bits in parallel.',
  keywords: ['shift register', 'register', 'serial', 'parallel', 'sipo', 'sequential'],
  pinCount: 16,
  pins: [
    ['CLR', 'RESET', 'in', { activeLow: true, note: 'Asynchronous clear.' }],
    ['J', 'INPUT', 'in', { note: 'Serial input, true side.' }],
    ['K̅', 'INPUT', 'in', { activeLow: true, note: 'Serial input, complement side.' }],
    ['A', 'INPUT', 'in'],
    ['B', 'INPUT', 'in'],
    ['C', 'INPUT', 'in'],
    ['D', 'INPUT', 'in'],
    ['GND', 'GROUND', 'power'],
    ['SH/LD', 'ENABLE', 'in', { note: 'Low loads the parallel inputs, high shifts.' }],
    ['CLK', 'CLOCK', 'in', { note: 'Rising edge triggered.' }],
    ['QD̅', 'OUTPUT', 'out'],
    ['QD', 'OUTPUT', 'out'],
    ['QC', 'OUTPUT', 'out'],
    ['QB', 'OUTPUT', 'out'],
    ['QA', 'OUTPUT', 'out'],
    ['VCC', 'POWER', 'power'],
  ],
  model: 'ic74195',
  propagationDelayNs: 18,
  maxClockMHz: 30,
  datasheet: {
    functionSummary:
      'On a rising edge: load A-D when SH/LD is low, otherwise shift QA->QB->QC->QD with the JK pair feeding QA.',
    notes: ['The first stage is a JK input: tie J high and K-bar low to shift in ones.'],
  },
});

export const TTL_74XX_DEFINITIONS: ComponentDefinition[] = [
  IC_7400,
  IC_7402,
  IC_7404,
  IC_7408,
  IC_7410,
  IC_7420,
  IC_7427,
  IC_7430,
  IC_7432,
  IC_7447,
  IC_7474,
  IC_7476,
  IC_7483,
  IC_7486,
  IC_7490,
  IC_74138,
  IC_74151,
  IC_74163,
  IC_74195,
];
